config/routes.rb
Rails.application.routes.draw do
  resources :notes do
    resources :date_notes, only: %i[new create edit update destroy]
  end
  resource :todos, only: %i[new create]
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/date_note.rb
class DateNote < ApplicationRecord
  belongs_to :note

  validates :date, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :date_notes

  validates :text, presence: true

  broadcasts_to ->(note) { [note.user, 'notes'] }, inserts_by: :prepend
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :date_note
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/date_notes_controller.rb
class DateNotesController < ApplicationController
  def new
    note = Note.find_by(id: params[:note_id])
    @date = note.date_notes.build
  end

  def edit
    @date_note = DateNote.find_by(id: params[:id])
  end

  def update
    @date = DateNote.find_by(id: params[:id])
    @date.update(params.require(:date_note).permit(:date))
    redirect_to note_path(@date.note), notice: 'Date was successfully updated'
  end

  def destroy
    @date = DateNote.find_by(id: params[:id])
    @date.destroy
    redirect_to note_path(@date.note), notice: 'Date was deleted updated'
  end

  def create
    note = Note.find_by(id: params[:note_id])
    @date_note = note.date_notes.build(params.require(:date_note).permit(:date))
    if @date_note.save
      return respond_to do |format|
        format.html { redirect_to note_path(note), notice: 'Date was successfully added' }
        format.turbo_stream
      end
    end

    render :new, status: :unprocessable_entity
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    case params[:as]
    when 'bill'
      session[:user_id] = User.find_by(name: 'Bill').id
    when 'john'
      session[:user_id] = User.find_by(name: 'John').id
    end

    redirect_to notes_path if session[:user_id].present?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = current_user.notes.order(created_at: :desc)
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(params.require(:note).permit(:text))
    if @note.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream { flash.now[:notice] = 'Quote was successfully created.' }
      end
      return true
    end

    render :new, status: :unprocessable_entity
  end

  def show
    @note = Note.find params[:id]
  end

  def edit
    @note = Note.find params[:id]
  end

  def update
    @note = Note.find params[:id]
    if @note.update(params.require(:note).permit(:text))
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream do
          flash.now[:notice] = 'Updated was successfully'
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @note = Note.find params[:id]
    @note.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.turbo_stream
    end
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def new
    @todo = Todo.new(date_note: DateNote.find(params[:date_note_id]))
  end

  def create
    todo_params = params.require(:todo).permit(:name, :date_note_id)
    @todo = Todo.create!(todo_params)
    redirect_to note_path(@todo.date_note.note)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/date_notes/_date_note.html.erb
<li>
  <div class="border">
    <%= date_note.date %>
    <br>
    <%= link_to 'Edit', [:edit, date_note.note, date_note] %>
    <%= button_to 'Delete', [date_note.note, date_note], method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>
    <%= link_to 'Add Todo', new_todos_path(date_note_id: date_note.id), data: { turbo_frame: '_top' } %>
  </div>
</li>

app/views/date_notes/_form.html.erb
<%= form_with(model: @date_note, url: [@date_note.note, @date_note]) do |form| %>
  <%= form.date_field :date, class: 'form-control' %>
  <%= form.submit 'Submit' %>
  <%= link_to 'Cancel', note_path(@date_note.note) %>
<% end %>

app/views/date_notes/create.turbo_stream.erb
<%= turbo_stream.prepend 'date_notes' do %>
  <%= render @date_note %>
<% end %>

<%= turbo_stream.replace dom_id(DateNote.new), '' %>

app/views/date_notes/edit.html.erb
<%= turbo_frame_tag @date_note do %>
  <%= render 'form' %>
<% end %>

app/views/date_notes/new.html.erb
<%= turbo_frame_tag dom_id(DateNote.new) do %>
  <% if @date.errors.any? %>
    <span><%= @date.errors.full_messages.to_sentence %></span>
  <% end %>
  <%= render 'form' %>
<% end %>

app/views/home/index.html.erb
<h1>Welcome to the notes app</h1>

<%= link_to 'Login as bill', root_path(as: 'bill') %>
<br>
<%= link_to 'Login as John', root_path(as: 'john') %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container my-4">
      <div class="col-md-4 m-auto">
        <%= render 'shared/message' %>
        <div id="flash" class="flash"></div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/notes/_blank.html.erb
 <p>You don't have any note</p>
<%= link_to "Start to add note", new_note_path %>

app/views/notes/_note.html.erb
<%= turbo_frame_tag dom_id(note) do %>
  <li>
    <%= note.text %>
    <%= link_to 'Open', note_path(note), data: { turbo_frame: '_top' } %>
    <%= link_to 'Edit', edit_note_path(note) %>
    <%= link_to 'Delete', note_path(note), data: { turbo_method: :delete } %>
  </li>
<% end %>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.prepend 'notes' do %>
  <%= render partial: 'notes/note', locals: { note: @note } %>
<% end %>
<%= turbo_stream.update 'new_note', '' %>

<%= turbo_stream.prepend 'flash' do %>
  <%= render partial: 'shared/message' %>
<% end %>

app/views/notes/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@note) %>
<% if @note.user.notes.blank? %>
  <%= turbo_stream.update Note.new do %>
    <%= render 'notes/blank' %>
  <% end %>
<% end %>

app/views/notes/edit.html.erb
<%= turbo_frame_tag @note do %>
  <% if @note.errors.full_messages.any? %>
    <span><%= @note.errors.full_messages.join(', ') %></span>
  <% end %>
  <%= form_with(model: @note) do |form| %>
    <%= form.text_field :text, class: 'form-control' %>
    <%= link_to 'Cancel', root_path %>
    <%= form.submit 'Update' %>
  <% end %>
<% end %>

app/views/notes/index.html.erb
<%= turbo_stream_from current_user, 'notes' %>

<h4>List of notes</h4>

<%= link_to 'Add new note', new_note_path, data: { turbo_frame: dom_id(Note.new) } %>

<hr>

<%= turbo_frame_tag Note.new do %>
  <% if @notes.none? %>
    <%= render 'blank' %>
  <% end %>
<% end %>

<ul>
  <%= turbo_frame_tag 'notes' do %>
    <% @notes.each do |note| %>
      <%= render note %>
    <% end %>
  <% end %>
</ul>

app/views/notes/new.html.erb
<%= turbo_frame_tag dom_id(@note) do %>
  <div class="my-4">
    <%= form_with(model: @note) do |form| %>
      <% if @note.errors.full_messages.any? %>
        <span><%= @note.errors.full_messages.join(',') %></span>
        <hr>
      <% end %>

      <%= form.label :text %>
      <%= form.text_field :text, class: 'form-control' %>
      <br>
      <%= link_to 'Cancel', notes_path %>
      <%= form.submit 'Create note' %>
    <% end %>
  </div>
<% end %>

app/views/notes/show.html.erb
<%= link_to 'Back', root_path %>
<hr>
<h1>Showing note</h1>

<p>
  <span><%= @note.text %></span>
</p>
<%= link_to 'Add date', new_note_date_note_path(@note), data: { turbo_frame: dom_id(DateNote.new) } %>
<hr>

<%= turbo_frame_tag dom_id(DateNote.new) %>

<ul>
  <%= turbo_frame_tag 'date_notes' do %>
    <% @note.date_notes.each do |date| %>
      <%= turbo_frame_tag date do %>
        <%= render date %>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/notes/update.turbo_stream.erb
<%= turbo_stream.replace 'flash', partial: 'shared/message' %>

app/views/shared/_message.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message">
    <%= message %>
  </div>
<% end %>

app/views/todos/new.html.erb
<h1>Add todo</h1>

<%= form_with(model: @todo, url: todos_path, method: :post) do |form| %>
  <%= form.text_field :name %>
  <%= form.hidden_field :date_note_id, value: params[:date_note_id] %>
  <%= form.submit 'Submit' %>
<% end %>